# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DaiYun' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DaiYun
  pod 'Alamofire', '~> 4.4'
  pod 'SnapKit','~> 3.2.0'
  pod 'SDWebImage', '~> 4.0.0-beta2'
  pod 'MBProgressHUD'
  pod 'FDFullscreenPopGesture', '1.1'
  pod 'SwifterSwift'
  pod 'MJRefresh'
  pod 'FMDB'
  pod 'MJExtension'
  pod 'ReactiveCocoa', '~> 5.0.2'
  pod 'NJKWebViewProgress'
  pod 'IQKeyboardManagerSwift', '4.0.9'

end
